### ISSUE TITLE
Fix color on admin graph

### ISSUE THREAD

**Issue by lanehunter-dev** [edlsto/fitlit#16]
#### The graph color for the _avg. active minutes_ doesn't match the theme we have for the rest of the graphs.
Let's change it to match the color of the graph above it.

**Comment by edlsto** [comment]
<img width="1413" alt="dashboard" src="https://user-images.githubusercontent.com/4350550/74385628-33b0db00-4db1-11ea-9560-df9636e5ac3c.png">
<img width="1411" alt="admin" src="https://user-images.githubusercontent.com/4350550/74385631-37446200-4db1-11ea-9c1a-6559f2277a74.png">

**Comment by edlsto** [comment]
I changed this color to match the color above.
